pull_request_rules:
  - name: Automatic squash and merge with success checks and the file docker-compose.yml is modified.
    conditions:
      - label=automation
      - label=ready-to-merge
      - files=docker-compose.yml
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: remove backport-skip label
    conditions:
      - label~=^backport-7
    actions:
      label:
        remove:
          - backport-skip
  - name: notify the backport policy
    conditions:
      - -label~=^backport
      - base=master
    actions:
      comment:
        message: |
          This pull request does not have a backport label. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you need to add the backport labels for the needed
          branches, such as:
          * `backport-7` is the label to automatically backport to the `7.x` branch.

          **NOTE**: `backport-skip` has been added to this pull request.
      label:
        add:
          - backport-skip
